### ISSUE TITLE
Magphys SFR and sSFR are the same

### ISSUE THREAD

**Issue by grudnick** [rfinn/Virgo#5]
Benedetta found this error.  She found it by plotting axs.plot(v.magphys[‘logsSFR-med’],v.magphys[‘logSFR-med’])

**Comment by rfinn** [comment]
fixed this with this commit, when updating virgoseds to use JM's v3 catalog 

https://github.com/rfinn/virgoseds/commit/5ecbbe25b7d73177c5b041565c4744431e8676c2

**Comment by rfinn** [comment]
issue closed
